MyLiveStock/Controllers/LayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyLiveStock.Models;

namespace MyLiveStock.Controllers
{
    public class LayoutController : Controller
    {
        // GET: Layout
        public PartialViewResult Navigation()
        {
            var model = new NavigationModel(Request.RawUrl);
            return PartialView("_Navigation", model);
        }

    }
}

MyLiveStock/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/Css/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Content/Css/AdminLTE.min.css" />
    <link rel="stylesheet" href="~/Content/Css/skins/skin-blue.css" />
    @*<link rel="stylesheet" href="~/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="~/fonts/font-awesome.min1.css">*@
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Ionicons -->
    @*<link rel="stylesheet" href="~/fonts/ionicons.min.css">
    <link rel="stylesheet" href="~/fonts/ionicons.min2.css">*@
    <link rel="stylesheet" href="~/Content/Css/skins/_all-skins.min.css" />
    @RenderSection("styles", required: false)
</head>
<body class="hold-transition skin-blue layout-boxed sidebar-mini">
    <div class="wrapper">
        @Html.Action("Navigation", "Layout")
        @RenderBody()
    </div>
    
    
    <script src="~/Scripts/jquery-2.1.4.js"></script>    
    <script src="~/Scripts/boostrap/bootstrap.min.js"></script>
    <script src="~/Scripts/Plugin/fastclick/fastclick.min.js"></script>
    <script src="~/Scripts/Plugin/slimScroll/jquery.slimscroll.min.js"></script>
    <script src="~/Scripts/app.min.js"></script>
    @*<script src="~/Scripts/demo.js"></script>*@

    @RenderSection("scripts", required : false)
</body>
</html>